"""Build the shipped exe, baking the shared HMAC secret in non-literally (D-09/D-10).

The real secret lives ONLY in the gitignored ``hmac_secret.local`` at the repo root
(the operator's safe copy, identical to the deployed Cloud Run secret). At build time
we read it, obfuscate it with the Plan 01 reversible scheme (base64-over-XOR — NOT a
committed literal, and not greppable in the artifact), and emit a generated
``_baked_secret.py`` carrying only the obfuscated form. ``main._load_hmac_secret``
imports that module when frozen and de-obfuscates it back at runtime.

The generated ``_baked_secret.py`` is written next to ``main.py`` so PyInstaller's
import analysis (``main.py`` does ``import _baked_secret`` under the frozen guard)
bundles it; it is also passed via ``--add-data`` as a belt-and-suspenders include and
declared as a hidden import. ``_baked_secret.py`` itself is build output (gitignored).

Run:  python build.py   ->  dist/pacman/pacman.exe
"""
import os

import PyInstaller.__main__

from settings import HMAC_SECRET_FILE_NAME
from leaderboard_crypto import obfuscate

ROOT = os.path.dirname(os.path.abspath(__file__))
SECRET_PATH = os.path.join(ROOT, HMAC_SECRET_FILE_NAME)
BAKED_MODULE_PATH = os.path.join(ROOT, "_baked_secret.py")


def _read_secret():
    """Read the gitignored real secret, failing loudly if it is absent.

    No fallback to the placeholder: a build must never silently ship without (or with
    a placeholder) secret. The operator creates ``hmac_secret.local`` from
    ``hmac_secret.example`` with the real value before building.
    """
    if not os.path.exists(SECRET_PATH):
        raise SystemExit(
            f"ERROR: {HMAC_SECRET_FILE_NAME} not found at the repo root.\n"
            f"Create it from hmac_secret.example with the REAL leaderboard HMAC secret "
            f"(the operator's safe copy, identical to the deployed Cloud Run secret) "
            f"before running build.py. It is gitignored and never committed."
        )
    with open(SECRET_PATH, "r", encoding="utf-8") as f:
        secret = f.read().strip()
    if not secret:
        raise SystemExit(f"ERROR: {HMAC_SECRET_FILE_NAME} is empty — put the real secret in it.")
    return secret


def _write_baked_module(secret):
    """Emit _baked_secret.py carrying the secret NON-LITERALLY (obfuscated).

    ``obfuscate`` returns base64-over-XOR ASCII bytes; we store that ASCII string, so
    a plain strings/grep of the artifact never surfaces the raw secret. The runtime
    counterpart is ``de_obfuscate`` in main._load_hmac_secret.
    """
    obfuscated = obfuscate(secret.encode("utf-8")).decode("ascii")
    content = (
        '"""Build-generated, gitignored. Carries the obfuscated HMAC secret (D-09/D-10).\n'
        "Never edit by hand; regenerated by build.py from hmac_secret.local.\n"
        'The value is base64-over-XOR obfuscated, NOT a literal secret."""\n'
        f'OBFUSCATED_SECRET = {obfuscated!r}\n'
    )
    with open(BAKED_MODULE_PATH, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    secret = _read_secret()
    _write_baked_module(secret)

    PyInstaller.__main__.run([
        "main.py",
        "--name=pacman",
        "--onedir",
        "--windowed",
        "--add-data=assets;assets",
        "--add-data=freesansbold.ttf;.",
        "--add-data=_baked_secret.py;.",
        "--hidden-import=_baked_secret",
    ])


if __name__ == "__main__":
    main()
